name: Run the README instructions - with stories - to ensure they work

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-mps:
    uses: pytorch/test-infra/.github/workflows/macos_job.yml@main
    with:
      runner: macos-14-xlarge 
      script: |
        set -x
        # NS: Remove previous installation  of torch first
        # as this script does not isntall anything into conda env but rather as system dep
        pip3 uninstall -y torch || true
        set -eou pipefail

        echo "::group::Print machine info"
        uname -a
        sysctl machdep.cpu.brand_string
        sysctl machdep.cpu.core_count
        echo "::endgroup::"

        # echo "::group::Install newer objcopy that supports --set-section-alignment"
        # yum install -y  devtoolset-10-binutils
        # export PATH=/opt/rh/devtoolset-10/root/usr/bin/:$PATH
        # echo "::endgroup::"

        echo "::group::Create script"
        python3 scripts/process-readme.py > ./readme-commands.sh
        echo "exit 1" >> ./readme-commands.sh
        echo "::endgroup::"

        echo "::group::Run This"
        grep -v login ./readme-commands.sh | sed  -e '1,$s/llama3/stories15M/g' > ./we-run-this.sh
        echo "*******************************************"
        cat ./we-run-this.sh
        echo "*******************************************"
        bash -x ./we-run-this.sh
        
        echo "tests complete"
        echo "*******************************************"
        echo "::endgroup::"
